// Coin card content (TASK-coingame-09). Editorial copy, versioned with code —
// deliberately NOT in the DB. Sources: cripto.md research (2026-07-04),
// coinfacts.md research (2026-07-04) — curated per its accuracy notes:
// no ATHs/market caps/rankings, no contested claims, no in-flux legal statuses.
// Excluded on purpose: real-world price-record facts (BNB >$1,000, DOGE ATH,
// HYPE ATH) — they contradict the deterministic fake tape on screen.
// Safe in client components: plain data, no imports.

export type CoinInfo = { intro: string; facts: string[] };

export const COIN_INFO: Record<string, CoinInfo> = {
  BTC: {
    intro:
      "Bitcoin is the world's first cryptocurrency — digital money you can send anywhere without banks, launched in 2009 by a mysterious figure named Satoshi Nakamoto. It runs on a global network of computers and is often called \"digital gold\" because only 21 million will ever exist.",
    facts: [
      "Bitcoin's creator, \"Satoshi Nakamoto,\" has never been identified and vanished from the internet around 2011.",
      "The very first Bitcoin block, mined January 3, 2009, hid a secret message quoting a Times headline about bank bailouts.",
      "Only 21 million bitcoins will ever exist — a hard cap written directly into the code.",
      "Bitcoin uses \"proof of work,\" where miners compete to solve puzzles using massive computing power to add new blocks.",
      "On \"Bitcoin Pizza Day\" (May 22, 2010), a programmer paid 10,000 BTC for two pizzas — a stash worth hundreds of millions of dollars today.",
      "Roughly every four years the mining reward is cut in half in an event called \"the halving,\" slowing the creation of new coins.",
      "Satoshi's untouched wallet is estimated to hold around 1.1 million BTC, making the anonymous creator one of the richest entities on Earth.",
      "The first person to receive a Bitcoin transaction was cryptographer Hal Finney, who got 10 BTC from Satoshi in January 2009.",
      "The entire Bitcoin whitepaper is only about nine pages long.",
      "\"HODL\" — crypto slang for never selling — comes from a drunken 2013 forum post titled \"I AM HODLING.\"",
      "Mt. Gox, once handling over 70% of all Bitcoin trades, began life as \"Magic: The Gathering Online eXchange\" — and collapsed in 2014 after losing about 850,000 BTC.",
      "In June 2011, a Mt. Gox hack briefly crashed Bitcoin's price from $17 to a single cent.",
      "In 2021, El Salvador became the first country to adopt Bitcoin as legal tender.",
      "The smallest unit of Bitcoin — 0.00000001 BTC — is called a \"satoshi.\"",
      "At the current halving schedule, the last bitcoin won't be mined until around the year 2140.",
      "Tesla bought $1.5 billion of Bitcoin in early 2021 and briefly accepted it for car purchases.",
      "In 2013 the FBI seized Silk Road, an online black market that ran on Bitcoin.",
      "Bitcoin has been declared \"dead\" hundreds of times by the press since 2010 — Warren Buffett alone accounts for at least eight of the obituaries.",
    ],
  },
  ETH: {
    intro:
      "Ethereum is a blockchain that works like a giant world computer — instead of just sending money, it runs \"smart contracts,\" self-executing programs that power apps, games, NFTs, and decentralized finance. Its native coin is called Ether (ETH).",
    facts: [
      "Ethereum was proposed in 2013 by Vitalik Buterin when he was just 19 years old, and launched in 2015.",
      "Buterin has said he was inspired to create Ethereum partly after a video game company nerfed his favorite World of Warcraft character.",
      "In 2022, Ethereum switched from proof of work to proof of stake in an event called \"The Merge,\" cutting its energy use by about 99.95%.",
      "Ethereum introduced smart contracts — code that runs automatically when conditions are met, with no middleman needed.",
      "Ethereum's 2014 crowdsale raised 31,000 BTC (about $18 million) from the public, at an average sale price of roughly $0.30 per ETH.",
      "Ethereum is the birthplace of NFTs, DeFi, and most stablecoins — many of which later spread to other blockchains.",
      "\"Gas\" is the fee you pay to use Ethereum, priced according to how much computing your transaction requires.",
      "Ethereum had several co-founders including Gavin Wood, who wrote the technical \"Yellow Paper\" and helped create its Solidity programming language.",
      "In 2016 a hacker drained 3.6 million ETH from \"The DAO\" — then the biggest crowdfund in history — by exploiting a single reentrancy bug.",
      "Ethereum hard-forked to reverse the DAO hack; the minority who refused kept the original chain alive as Ethereum Classic.",
      "The Merge was likened to swapping a plane's engine mid-flight — the network never went down during the switch.",
      "Since the 2021 EIP-1559 upgrade, part of every transaction fee is permanently \"burned,\" sometimes making ETH deflationary.",
      "The name Ethereum comes from \"aether\" — the invisible medium once believed to fill the universe.",
      "Buterin co-founded Bitcoin Magazine as a teenager, then took a $100,000 Thiel Fellowship and dropped out of university to build Ethereum.",
      "A 2017 bug in the Parity wallet permanently froze about $150 million in ETH — and this time there was no rescue fork.",
      "In 2021 Buterin donated over $1 billion of SHIB tokens to India's COVID relief fund, crashing the memecoin in the process.",
      "An Estonian banker reportedly lost access to 250,000 ETH by misplacing his private key.",
      "Under proof of stake, an ordinary laptop can run an Ethereum validator — no warehouse of mining rigs required.",
    ],
  },
  BNB: {
    intro:
      "BNB is the token of Binance, one of the world's largest crypto exchanges, and started as a way to get discounts on trading fees. Today it also powers the BNB Chain, a fast blockchain for apps and DeFi.",
    facts: [
      "BNB launched in July 2017 through an ICO that sold tokens for about 15 cents each and raised roughly $15 million.",
      "BNB now stands for \"Build and Build\" after a 2022 rebrand — it originally meant \"Binance Coin.\"",
      "Binance regularly \"burns\" (permanently destroys) BNB, aiming to shrink the supply from 200 million down to 100 million.",
      "BNB started life as a token on Ethereum before migrating to Binance's own blockchain in 2019.",
      "BNB Chain uses \"Proof of Staked Authority,\" a system with a limited set of vetted validators built for speed.",
      "BNB's burns are automated through \"Auto-Burn,\" adjusting the amount based on price and network activity each quarter.",
      "Binance was founded by Changpeng Zhao — \"CZ\" — who built it into the world's largest crypto exchange within months.",
      "For years Binance let anyone trade with just an email address; full identity checks only arrived in 2021.",
      "In October 2022 hackers hit a BNB Chain bridge for around $570 million — validators halted the entire network and froze much of the loot.",
      "In 2023 Binance pleaded guilty to US charges and paid $4.3 billion — among the largest corporate penalties in American history.",
      "The DOJ said Binance \"became the world's largest crypto exchange in part because of the crimes it committed.\"",
      "CZ stepped down as CEO, paid a $50 million personal fine, and served four months in prison — prosecutors had asked for three years.",
      "In October 2025, President Trump pardoned CZ.",
      "BNB pays the gas on BNB Smart Chain, which runs Ethereum-style apps almost out of the box.",
    ],
  },
  XRP: {
    intro:
      "XRP is a cryptocurrency built for fast, cheap money transfers across borders, designed to move value between currencies in seconds. It's closely tied to the company Ripple and settles transactions in 3–5 seconds for a tiny fraction of a cent.",
    facts: [
      "All 100 billion XRP were created at once in 2012 — none are \"mined\" like Bitcoin.",
      "XRP doesn't use mining or staking; instead trusted validators reach agreement in a unique consensus process, settling payments in 3–5 seconds.",
      "An early software bug wiped out the first 32,569 ledgers, so XRP's verifiable public history begins at ledger 32,570.",
      "XRP was designed as a \"bridge currency\" to help banks move money between different national currencies.",
      "In 2017 Ripple locked 55 billion XRP into escrow, releasing up to 1 billion per month to reassure the market about supply.",
      "The SEC sued Ripple in December 2020; a landmark 2023 ruling found XRP itself is not a security when sold to the public.",
      "XRP uses almost no energy — a single transaction is often compared to the energy of one Google search.",
      "Ripple's founders gifted 80 billion XRP (80% of the supply) to the company to fund development.",
      "XRP began with a 2011 forum thread titled simply \"Bitcoin without mining.\"",
      "Co-founder Jed McCaleb also founded Mt. Gox — and after leaving Ripple, went on to create Stellar.",
      "The company behind XRP changed names three times: NewCoin, then OpenCoin, then Ripple Labs, now just Ripple.",
      "The 2023 court ruling cut both ways: XRP sold to the public wasn't a security, but Ripple's direct sales to institutions were.",
      "Ripple was ordered to pay a $125 million penalty in 2024; both sides dropped their appeals in 2025, ending the five-year fight.",
      "The \"Hinman emails,\" pried loose during the lawsuit, revealed the SEC itself disagreed internally on how to classify crypto.",
      "Banks including Santander and Standard Chartered have piloted Ripple's payment technology.",
      "MoneyGram walked away from its Ripple partnership within weeks of the SEC suit landing in 2020.",
      "The XRP Ledger has had a built-in decentralized exchange since 2012 — years before \"DEX\" became a buzzword.",
    ],
  },
  SOL: {
    intro:
      "Solana is a super-fast blockchain built for speed and low fees, capable of handling thousands of transactions per second. It's a popular home for NFTs, DeFi, and meme coins, and its coin is called SOL.",
    facts: [
      "Solana was dreamed up by Anatoly Yakovenko, a former Qualcomm engineer, who wrote its founding whitepaper in 2017.",
      "It's named after Solana Beach, a small town near San Diego where the founders lived and surfed while working at Qualcomm.",
      "Solana's signature innovation, \"Proof of History,\" timestamps transactions to help the network order them at high speed.",
      "The project was originally called \"Loom\" but rebranded to avoid confusion with another crypto project.",
      "Solana has suffered several notable network outages, at one point going offline for about 17 hours in September 2021.",
      "Solana pairs proof of stake with Proof of History and can process thousands of transactions per second at very low fees.",
      "SOL crashed hard after the 2022 collapse of the FTX exchange, a major backer — then staged a huge recovery.",
      "A second independent software client called \"Firedancer\" was built to make the network more reliable after its outage-plagued years.",
      "Solana's smallest unit is the \"lamport,\" named after computer scientist Leslie Lamport.",
      "Solana's genesis block landed on March 16, 2020 — the same week as the COVID market crash.",
      "FTX and Alameda once controlled an estimated 10–15% of the entire SOL supply — skeptics dubbed Solana ecosystem tokens \"Sam coins.\"",
      "The 2022 Wormhole bridge hack drained over $320 million — trading firm Jump covered the entire loss out of its own pocket.",
      "An August 2022 hack emptied over 9,000 Solana wallets at once, traced to leaked keys from a single wallet app.",
      "One outage was caused by bots hammering an NFT mint; another by an infinite recompile loop that halted the chain for five hours.",
      "Visa settles stablecoin payments on Solana, and Google Cloud runs a validator node.",
      "Solana became the home of the memecoin boom, with launchpads like pump.fun minting thousands of tokens a day.",
      "A running community motto from the lean years: \"just one more hard quarter.\"",
    ],
  },
  TRX: {
    intro:
      "TRON is a blockchain focused on cheap, fast transactions and digital content, founded by entrepreneur Justin Sun in 2017. Today it's one of the biggest networks in the world for moving stablecoins like USDT.",
    facts: [
      "TRON was founded in 2017 by Justin Sun, a charismatic entrepreneur once named to Forbes' 30 Under 30.",
      "TRON acquired the file-sharing pioneer BitTorrent in 2018, bringing millions of users into its ecosystem.",
      "TRON uses \"Delegated Proof of Stake,\" where holders vote for 27 \"Super Representatives\" who validate transactions.",
      "TRON hosts the largest share of the stablecoin Tether (USDT) of any blockchain — tens of billions of dollars' worth.",
      "TRON transactions are extremely cheap, often costing about a cent, making it popular for global remittances.",
      "The smallest unit of TRX is called a \"sun,\" named after founder Justin Sun.",
      "TRON started as a token on Ethereum before launching its own blockchain in 2018 — celebrated with a symbolic \"Independence Day\" burn of 1 billion TRX.",
      "Critics note TRON is relatively centralized, with just 27 block-producing validators and heavy influence from Justin Sun.",
      "TRON's $70 million ICO closed just days before China banned ICOs in September 2017.",
      "Before founding TRON, Justin Sun was Ripple's representative for Greater China.",
      "Sun paid $4.6 million at a charity auction for lunch with Warren Buffett — postponed it, then finally showed up and gifted Buffett a phone loaded with crypto.",
      "In 2024 Sun bought the famous duct-taped-banana artwork for about $6.2 million — and ate the banana at a press conference.",
      "Sun served as Grenada's ambassador to the World Trade Organization from 2021 to 2023.",
      "The SEC sued Sun in 2023, alleging wash trading and undisclosed celebrity promotions involving Lindsay Lohan and Jake Paul.",
      "In 2022 the Caribbean nation of Dominica designated TRON its \"national blockchain.\"",
      "Sun once spent $500,000 on an NFT of a rock — and won a roughly $28 million bid for a Blue Origin spaceflight he took in 2025.",
      "Sun also owns the crypto exchanges Poloniex and HTX (formerly Huobi).",
    ],
  },
  HYPE: {
    intro:
      "Hyperliquid is a newer blockchain (launched 2024) built specifically for fast, on-chain trading of crypto \"perpetual\" futures, rivaling big centralized exchanges. Its token, HYPE, powers the network and made headlines for one of the largest airdrops in crypto history.",
    facts: [
      "Hyperliquid gave away its HYPE token on November 29, 2024 — 310 million HYPE (31% of the 1 billion supply) sent to about 94,000 wallets in one of the largest airdrops ever.",
      "The project famously took no venture capital money, allocating the vast majority of its tokens to the community instead.",
      "Hyperliquid was founded by Jeff Yan, a Harvard graduate and former Hudson River Trading quant, with a small team.",
      "Its blockchain runs on a custom consensus called \"HyperBFT\" and claims to process hundreds of thousands of orders per second.",
      "Unlike centralized exchanges, Hyperliquid keeps its entire order book fully on-chain and transparent.",
      "HYPE has a fixed maximum supply of 1 billion tokens, and the protocol uses most of its trading fees to buy back and burn HYPE.",
      "The airdrop was so generous the average recipient's allocation was worth $45,000–$50,000 at the time.",
      "Founder Jeff Yan's manifesto ran four lines: \"No investors. No paid market makers. No fees to the dev team. No insiders.\"",
      "Yan reportedly turned down venture funding that valued the project around $1 billion — and kept the team at about a dozen people.",
      "Yan won silver at the 2012 International Physics Olympiad, then came back for gold in 2013.",
      "His \"@chameleon_jeff\" handle comes from a fascination with chameleons.",
      "In 2025 an attacker used the illiquid JELLY memecoin to stick Hyperliquid's vault with a toxic short — validators voted to delist it within minutes.",
      "The lightning-fast JELLY vote saved the vault but raised questions about how decentralized Hyperliquid really is — one rival CEO called it potentially \"FTX 2.0.\"",
      "During crypto's largest-ever liquidation day in October 2025, Hyperliquid reported 100% uptime and zero bad debt.",
      "Hyperliquid launched HyperEVM in 2025, letting Ethereum-style apps run alongside its exchange.",
      "By 2025 the roughly 11-person team was generating over a billion dollars in annualized revenue.",
    ],
  },
  DOGE: {
    intro:
      "Dogecoin started in 2013 as a joke based on the \"Doge\" Shiba Inu meme, but grew into one of the most famous cryptocurrencies in the world. It's known for its friendly community, tiny transaction fees, and celebrity fans like Elon Musk.",
    facts: [
      "Dogecoin was created in 2013 by engineers Billy Markus and Jackson Palmer as a parody of the crypto craze.",
      "Its logo is Kabosu, a real Japanese Shiba Inu adopted from a shelter, made famous by the \"Doge\" meme.",
      "Co-founder Billy Markus sold all his Dogecoin in 2015 to buy a used Honda Civic — a stash worth millions at later peaks.",
      "Dogecoin's community once raised funds to sponsor a NASCAR driver and send the Jamaican bobsled team to the 2014 Olympics.",
      "Unlike Bitcoin, Dogecoin has no supply cap — about 5 billion new coins are created every year.",
      "Dogecoin uses proof of work but with fast one-minute blocks, making it quick and cheap for tipping online.",
      "SpaceX agreed to launch a satellite called \"DOGE-1\" to the Moon, funded entirely with Dogecoin.",
      "Markus built Dogecoin in about three hours — much of it reportedly spent changing the font to Comic Sans.",
      "Palmer tweeted \"Investing in Dogecoin, pretty sure it's the next big thing\" as a joke — before the coin even existed.",
      "Dogecoin is a fork of Luckycoin, itself a fork of Litecoin — a joke built on a joke built on serious code.",
      "Markus goes by \"Shibetoshi Nakamoto\" online.",
      "Co-founder Jackson Palmer quit crypto entirely in 2015, later calling it \"inherently right-wing, hyper-capitalistic technology.\"",
      "Elon Musk — the \"Dogefather\" — was once elected \"CEO of Dogecoin\" in a joke Twitter poll, and briefly made the Doge the Twitter logo in 2023.",
      "The community's \"Doge4Water\" campaign raised over $30,000 to drill water wells in Kenya.",
      "Dogecoin's motto: \"Do Only Good Everyday.\"",
      "Dogecoin can be \"merge-mined\" with Litecoin — miners secure both chains at once.",
      "Vitalik Buterin, Ethereum's creator, sits on the advisory board of the Dogecoin Foundation.",
    ],
  },
  LINK: {
    intro:
      "Chainlink is a network that acts as a bridge between blockchains and the real world, feeding smart contracts reliable outside data like prices, weather, and sports scores. Its token, LINK, pays the operators who deliver that data.",
    facts: [
      "Chainlink solves the \"oracle problem\" — blockchains can't reach outside data on their own, so Chainlink securely delivers it.",
      "It was co-founded in 2017 by Sergey Nazarov and Steve Ellis, with a whitepaper co-authored by Cornell professor Ari Juels.",
      "Chainlink raised exactly $32 million in its 2017 ICO at an average price near $0.09 per LINK.",
      "Instead of trusting one source, Chainlink gathers data from many independent nodes and cross-checks it for accuracy.",
      "Node operators must stake LINK as collateral and can be penalized for supplying bad data.",
      "Chainlink has enabled trillions of dollars in transaction value and secures a large majority of the DeFi oracle market.",
      "Banking giant SWIFT has tested Chainlink's cross-chain technology for moving tokenized assets between systems.",
      "LINK has a fixed maximum supply of 1 billion tokens.",
      "Chainlink's devoted community is nicknamed the \"LINK Marines.\"",
      "LINK's smallest unit is the \"Juel,\" named after whitepaper co-author Ari Juels.",
      "In 2025 the US Department of Commerce began publishing official GDP data on-chain via Chainlink — a first for a federal agency.",
      "In 2020 an anonymous \"Zeus Capital\" report called LINK a fraud — a real UK firm of the same name had to publicly disavow it.",
      "Chainlink's price feeds power DeFi giants like Aave and Compound.",
      "Chainlink launched CCIP in 2023 to connect different blockchains, and has worked with DTCC, the world's largest securities settlement system.",
      "Chainlink absorbed Cornell research projects \"Town Crier\" and \"DECO\" to bring trusted hardware and zero-knowledge proofs to oracles.",
      "Co-founder Sergey Nazarov studied philosophy and management at NYU before finding his way to smart contracts.",
    ],
  },
  HBAR: {
    intro:
      "Hedera is a fast, energy-efficient network for building apps and moving value — but it's not technically a blockchain, using a different design called \"hashgraph.\" It's governed by a council of major global companies, and its coin is called HBAR.",
    facts: [
      "Hedera uses \"hashgraph\" instead of a blockchain — data forms a web (a directed graph) rather than a single chain of blocks.",
      "The hashgraph algorithm was invented by Dr. Leemon Baird, who co-founded Hedera with Mance Harmon; both worked at the U.S. Air Force Academy.",
      "Hedera is run by a \"Governing Council\" of major companies — members have included Google, IBM, LG, and Deutsche Telekom — each with one equal vote.",
      "The council's one-company-one-vote structure was modeled on Visa's original 1968 governance framework.",
      "Hedera reaches agreement using \"gossip about gossip\" and \"virtual voting,\" and is asynchronous Byzantine Fault Tolerant (aBFT).",
      "Transactions cost about $0.0001 and the network is carbon-negative, buying offsets that more than cover its tiny energy use.",
      "All 50 billion HBAR were created at the network's 2018 launch — the supply is capped and can't grow without a unanimous council vote.",
      "In 2024 Hedera donated its entire codebase to the Linux Foundation (as a project called \"Hiero\") — reportedly the first public network to do so.",
      "Hedera's hashgraph technology was patented, then later open-sourced under the Apache 2.0 license in 2022.",
      "Hashgraph's design makes Hedera essentially impossible to fork.",
      "Inventor Leemon Baird holds a Carnegie Mellon PhD and spent years writing formal mathematical proofs of hashgraph's security.",
      "Fees are pegged to the US dollar rather than HBAR, so transaction costs stay stable no matter where the coin trades.",
      "Transactions reach mathematically final confirmation in under five seconds — no waiting for block confirmations.",
      "Hashgraph processes transactions in parallel instead of one block at a time.",
      "Hedera's 2018 launch event drew 1,000 people in person and over 100,000 on the livestream.",
      "The founders describe their goal as building a \"100-year company\" — a \"trust layer of the internet.\"",
      "FedEx joined the Hedera Council in 2026 for supply-chain work.",
      "Council members serve limited terms, so no single company can entrench itself.",
    ],
  },
};
