-- Curated 30-ticker pool for 1K Daily. Names/sectors for display only; every
-- price in the game comes from the deterministic fake feed (lib/prices.ts).
insert into stockgame_ticker (symbol, name, sector) values
  ('NVDA', 'NVIDIA',            'Semis'),
  ('AAPL', 'Apple',             'Tech'),
  ('MSFT', 'Microsoft',         'Tech'),
  ('AMZN', 'Amazon',            'Consumer'),
  ('GOOG', 'Alphabet',          'Tech'),
  ('META', 'Meta Platforms',    'Tech'),
  ('TSLA', 'Tesla',             'Auto'),
  ('AMD',  'AMD',               'Semis'),
  ('AVGO', 'Broadcom',          'Semis'),
  ('NFLX', 'Netflix',           'Media'),
  ('CRM',  'Salesforce',        'Software'),
  ('ORCL', 'Oracle',            'Software'),
  ('COST', 'Costco',            'Retail'),
  ('WMT',  'Walmart',           'Retail'),
  ('JPM',  'JPMorgan Chase',    'Banks'),
  ('GS',   'Goldman Sachs',     'Banks'),
  ('V',    'Visa',              'Payments'),
  ('MA',   'Mastercard',        'Payments'),
  ('UNH',  'UnitedHealth',      'Health'),
  ('LLY',  'Eli Lilly',         'Pharma'),
  ('PFE',  'Pfizer',            'Pharma'),
  ('XOM',  'ExxonMobil',        'Energy'),
  ('CVX',  'Chevron',           'Energy'),
  ('BA',   'Boeing',            'Industrial'),
  ('CAT',  'Caterpillar',       'Industrial'),
  ('DIS',  'Disney',            'Media'),
  ('NKE',  'Nike',              'Consumer'),
  ('SBUX', 'Starbucks',         'Consumer'),
  ('COIN', 'Coinbase',          'Crypto'),
  ('PLTR', 'Palantir',          'Software')
on conflict (symbol) do nothing;
